pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/dbserver-dev/nestproject.git'
            }
        }

        stage('Build Frontend') {
            steps {
                sh 'docker build -t vue -f docker/frontend.Dockerfile .'
            }
        }

        stage('Build Backend') {
            steps {
                sh 'docker build -t nest -f docker/backend.Dockerfile .'
            }
        }

        stage('Push Docker Images') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker tag vue your-dockerhub-id/vue:latest'
                    sh 'docker push your-dockerhub-id/vue:latest'

                    sh 'docker tag nest your-dockerhub-id/nest:latest'
                    sh 'docker push your-dockerhub-id/nest:latest'
                }
            }
        }

        stage('Deploy') {
            steps {
                sshagent(['my-server-ssh']) {
                    sh '''
                    ssh ubuntu@192.168.0.99 "
                        docker pull your-dockerhub-id/vue:latest &&
                        docker pull your-dockerhub-id/nest:latest &&
                        docker-compose down &&
                        docker-compose up -d
                    "
                    '''
                }
            }
        }
    }
}
